//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftwareTrails.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoftwareTrails.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to Elevate Permissions.
        /// </summary>
        internal static string ElevatingCaption {
            get {
                return ResourceManager.GetString("ElevatingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to run SoftwareTrailsAdmin.exe to regsvr32 the profiler assembly which needs elevation to administrator. Click Yes if you want to allow this..
        /// </summary>
        internal static string ElevatingRegister {
            get {
                return ResourceManager.GetString("ElevatingRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t copy {0} into the target directory &apos;{1}&apos;.
        /// </summary>
        internal static string FileCopyError {
            get {
                return ResourceManager.GetString("FileCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph contains {0} nodes {1} links, are you sure you want to expand them all?.
        /// </summary>
        internal static string LargeGraphWarning {
            get {
                return ResourceManager.GetString("LargeGraphWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Graph Warning.
        /// </summary>
        internal static string LargeGraphWarningCaption {
            get {
                return ResourceManager.GetString("LargeGraphWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probable reason is that the target process didn&apos;t load the .NET v4.0 runtime, and so the profiler was not loaded in the target process..
        /// </summary>
        internal static string ProfilerNotFound {
            get {
                return ResourceManager.GetString("ProfilerNotFound", resourceCulture);
            }
        }
    }
}
